cron:
  name: AbiFanout
  queue: fanout
  job: abis
  schedule: '*/15 * * * *'
  start: false

abis:
  - abiPath: 'erc4626'
    things: {
      label: 'vault',
      filter: [
        { field: 'erc4626', op: '=', value: 'true' },
        { field: 'yearn', op: '!=', value: 'true' }
      ]
    }

  # - abiPath: 'yearn/3/registry3'
  #   sources: [
  #     { chainId: 1, address: '0xd40ecF29e001c76Dcc4cC0D9cd50520CE845B038', inceptBlock: 21176924 },
  #   ]

  - abiPath: 'yearn/3/vaultFactory'
    sources: [
      # { chainId: 1, address: '0xE9E8C89c8Fc7E8b8F23425688eb68987231178e5', inceptBlock: 18385809 },
      # { chainId: 1, address: '0x444045c5C13C246e117eD36437303cac8E250aB0', inceptBlock: 19372662 },
      # { chainId: 1, address: '0x770D0d1Fb036483Ed4AbB6d53c1C88fb277D812F', inceptBlock: 21087110 },
      { chainId: 98867, address: '0x770D0d1Fb036483Ed4AbB6d53c1C88fb277D812F', inceptBlock: 455452 },
    ]

  - abiPath: 'yearn/3/vault'
    things: {
      label: 'vault',
      filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    }

  - abiPath: 'yearn/3/strategy'
    things: {
      label: 'strategy',
      filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    }

  - abiPath: 'yearn/3/accountant'
    things: {
      label: 'accountant',
      filter: []
    }

  - abiPath: 'yearn/3/debtManagerFactory'
    sources: [
      # { chainId: 1, address: '0xfCF8c7C43dedd567083B422d6770F23B78D15BDe', inceptBlock: 19381894 },
    ]

  - abiPath: 'yearn/3/debtAllocator'
    things: {
      label: 'debtAllocator',
      filter: []
    }

  - abiPath: 'yearn/3/roleManagerFactory'
    sources: [
      # { chainId: 1, address: '0xca12459a931643BF28388c67639b3F352fe9e5Ce', inceptBlock: 20974081 },
    ]

  - abiPath: 'yearn/3/roleManager'
    things: {
      label: 'roleManager',
      filter: []
    }
